name: macOS Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos:
    name: Build on ${{ matrix.runs_on }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        runs_on: [macos-13, macos-14]
        python-version: ['3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Show env
        run: |
          sw_vers
          uname -a
          python -V

      - name: Determine arch
        run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Set macOS deployment target
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV

      - name: Install freetype (Homebrew) and export path
        shell: bash
        run: |
          set -euxo pipefail

          # Locate brew reliably across macOS-13 (Intel) and macOS-14 (ARM)
          if command -v brew >/dev/null 2>&1; then
            BREW=$(command -v brew)
          elif [ -x /usr/local/bin/brew ]; then
            BREW=/usr/local/bin/brew
          elif [ -x /opt/homebrew/bin/brew ]; then
            BREW=/opt/homebrew/bin/brew
          else
            echo "Homebrew not found" >&2
            exit 1
          fi
          echo "Using brew at: $BREW"

          # Avoid API JSON/JWS issues and auto-update flakiness on older images
          export HOMEBREW_NO_AUTO_UPDATE=1
          export HOMEBREW_NO_ANALYTICS=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          export HOMEBREW_NO_INSTALL_FROM_API=1

          # Helper: retry a command up to 3 times
          retry() {
            local n=0
            local max=3
            local delay=10
            until "$@"; do
              exit_code=$?
              n=$((n+1))
              if [ $n -ge $max ]; then
                echo "Command failed after $n attempts: $*" >&2
                return $exit_code
              fi
              echo "Retrying ($n/$max): $*" >&2
              sleep $delay
            done
            return 0
          }

          # If freetype already exists, skip install; otherwise reset taps and install
          if ! "$BREW" --prefix freetype >/dev/null 2>&1; then
            echo "freetype not installed; resetting brew taps and installing deps..."
            retry "$BREW" update-reset || true
            # ensure core tap exists
            "$BREW" tap homebrew/core || true
            retry "$BREW" install freetype harfbuzz libpng brotli graphite2
          else
            echo "freetype already installed: $($BREW --prefix freetype)"
            # still ensure other deps present but don't fail build if missing
            "$BREW" install harfbuzz libpng brotli graphite2 || true
          fi

          FTBREW_PREFIX=$("$BREW" --prefix freetype)
          echo "FREETYPE_PREFIX=${FTBREW_PREFIX}" >> $GITHUB_ENV
          if [ -f "${FTBREW_PREFIX}/lib/libfreetype.6.dylib" ]; then
            FREETYPE_DYLIB="${FTBREW_PREFIX}/lib/libfreetype.6.dylib"
            echo "FREETYPE_DYLIB=${FREETYPE_DYLIB}" >> $GITHUB_ENV
          else
            # Fallback for potential versioned names
            CANDIDATE=$(ls -1 ${FTBREW_PREFIX}/lib/libfreetype*.dylib 2>/dev/null | head -n 1 || true)
            if [ -n "$CANDIDATE" ]; then
              FREETYPE_DYLIB="$CANDIDATE"
              echo "FREETYPE_DYLIB=$FREETYPE_DYLIB" >> $GITHUB_ENV
            else
              echo "Failed to locate libfreetype dylib under ${FTBREW_PREFIX}/lib" >&2
              exit 1
            fi
          fi
          echo "Using FREETYPE_DYLIB=$FREETYPE_DYLIB"
          ls -l "$FREETYPE_DYLIB"

          # Only bundle freetype to avoid conflicts with cv2 hook-collected libs
          ADD_BINARIES=("$FREETYPE_DYLIB:cv2/.dylibs/libfreetype.6.dylib")

          # Export composed add-binary args
          # Stage dylibs and normalize their internal dependency paths to @loader_path
          STAGED_DIR=./macos_dylibs
          mkdir -p "$STAGED_DIR"
          DYLIB_NAMES=()
          STAGED_BINARIES=()
          for item in "${ADD_BINARIES[@]}"; do
            # item format: src:dest
            SRC_PATH="${item%%:*}"
            BASENAME=$(basename "$SRC_PATH")
            cp -f "$SRC_PATH" "$STAGED_DIR/$BASENAME"
            DYLIB_NAMES+=("$BASENAME")
            STAGED_BINARIES+=("$STAGED_DIR/$BASENAME:cv2/.dylibs/$BASENAME")
          done

          echo "Staged dylibs in $STAGED_DIR:" && ls -l "$STAGED_DIR" | cat

          # Rewrite dependent paths inside staged dylibs
          for f in "$STAGED_DIR"/*.dylib; do
            [ -e "$f" ] || continue
            echo "Rewriting dependencies for $f"
            # Optional: set install name id (not required for non-shared re-export)
            install_name_tool -id "@rpath/$(basename "$f")" "$f" || true
            while IFS= read -r line; do
              # otool -L lines look like: '\t/path/to/libfreetype.6.dylib (compatibility version 6.0.0, current version 6.0.0)'
              dep=$(echo "$line" | awk '{print $1}')
              case "$dep" in
                /*|@rpath/*|@loader_path/*)
                  base=$(basename "$dep")
                  for n in "${DYLIB_NAMES[@]}"; do
                    if [ "$base" = "$n" ]; then
                      if [ "$dep" != "@loader_path/$base" ]; then
                        echo "  change $dep -> @loader_path/$base"
                        install_name_tool -change "$dep" "@loader_path/$base" "$f" || true
                      fi
                    fi
                  done
                  ;;
              esac
            done < <(otool -L "$f" | tail -n +2)
          done

          # Persist staged binary pairs to a file to avoid quoting issues across steps
          STAGED_BINS_FILE=./staged_bins.txt
          : > "$STAGED_BINS_FILE"
          for item in "${STAGED_BINARIES[@]}"; do
            printf '%s\n' "$item" >> "$STAGED_BINS_FILE"
          done
          echo "STAGED_BINS_FILE=$STAGED_BINS_FILE" >> $GITHUB_ENV
          echo "Wrote $(wc -l < "$STAGED_BINS_FILE") binary mappings to $STAGED_BINS_FILE"

      - name: Upgrade pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install project and build tool
        run: |
          python -m pip install .
          python -m pip install pyinstaller

      - name: Build single-file binary with PyInstaller
        run: |
          CMD='pyinstaller --clean -F -n pdf2zh \
            --add-data "pdf2zh_next/assets:pdf2zh_next/assets" \
            --add-data "pdf2zh_next/gui_translation.yaml:pdf2zh_next"'
          if [ -f "$STAGED_BINS_FILE" ]; then
            while IFS= read -r line; do
              [ -n "$line" ] || continue
              CMD+=" --add-binary \"$line\""
            done < "$STAGED_BINS_FILE"
          fi
          CMD+=" pdf2zh_next/main.py"
          echo "Running: $CMD"
          eval "$CMD"

      - name: Smoke test binary
        run: |
          ./dist/pdf2zh --version | cat
          ./dist/pdf2zh --help | head -n 50 | cat

      - name: Test - Translate a PDF file with plain text only
        run: |
          ./dist/pdf2zh ./test/file/translate.cli.plain.text.pdf --output ./test/file

      - name: Test - Translate a PDF file figure
        run: |
          ./dist/pdf2zh ./test/file/translate.cli.text.with.figure.pdf --output ./test/file

      - name: Delete offline assets and cache (macOS)
        shell: bash
        run: |
          echo "==== 删除离线资源包（如存在）===="
          OFFLINE_ZIP=$(ls -1 ./dist/offline_assets_*.zip 2>/dev/null | head -n 1 || true)
          if [ -n "$OFFLINE_ZIP" ]; then
            echo "找到离线资源包: $OFFLINE_ZIP"
            rm -f "$OFFLINE_ZIP"
            echo "已删除离线资源包"
          else
            echo "未找到离线资源包"
          fi
          echo "==== 删除缓存目录 ~/.cache/babeldoc ===="
          rm -rf "$HOME/.cache/babeldoc" || true

      - name: Test - Translate without offline assets
        run: |
          ./dist/pdf2zh ./test/file/translate.cli.plain.text.pdf --output ./test/file

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: macos-test-results-${{ env.ARCH }}
          path: ./test/file/

      - name: Prepare package
        run: |
          mkdir -p release
          mkdir -p "release/pdf2zh-next-macos-${ARCH}"
          cp dist/pdf2zh "release/pdf2zh-next-macos-${ARCH}/"
          cp README.md LICENSE "release/pdf2zh-next-macos-${ARCH}/"
          cd release
          ZIP_NAME="pdf2zh-next-${{ github.ref_type == 'tag' && github.ref_name || 'dev' }}-macos-${ARCH}.zip"
          /usr/bin/zip -r "$ZIP_NAME" "pdf2zh-next-macos-${ARCH}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf2zh-next-macos-${{ env.ARCH }}
          path: release/*.zip

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.zip


